#!/usr/bin/perl -w

use esmith::Build::CreateLinks  qw(:all);
use File::Path;

#--------------------------------------------------
# actions for user-create event nethserver-puppet-update
#--------------------------------------------------
$event = "nethserver-puppet-update";
event_actions($event,
              'nethserver-puppet-conf' => '20',
              'runlevel-adjust' => '30',
    );
event_services($event, 
                'puppet' => 'restart'
    );
event_templates($event, "/etc/sysconfig/puppet");

#--------------------------------------------------
# actions for user-create event nethserver-puppet-uninstall
#--------------------------------------------------
$event = "nethserver-puppet-uninstall";
event_actions($event,
              'nethserver-puppet-uninstall' => '20',
              'runlevel-adjust' => '30',
    );


exit 0;

